### ISSUE TITLE
make webpage responsive 

### ISSUE THREAD

**Issue by JVJplus** [JVJplus/Forkify#1]
make the webpage mobile friendly by changing grid template.

**Comment by ezekielnizamani** [comment]
Hello, can you assign me this task?

**Comment by saintaze** [comment]
is it being worked on or should I take it?

**Comment by JVJplus** [comment]
> is it being worked on or should I take it?

It is being worked on but you can also work on into it and be creative, and if we like it we will merge it!

**Comment by JVJplus** [comment]
thanks @saintaze for your work!
