### ISSUE TITLE
auto scroll to recipe view on clicking on the list of dishes after searching.

### ISSUE THREAD

**Issue by JVJplus** [JVJplus/Forkify#3]
Hi,
To improve the ux, we can add a auto scroll feature on small screen sizes.
after searching when the list of recipes appears, on clicking any of the recipe nothing visually happens after changes are done below that (which is hidding and we need to scroll to view it), it would be amazing if its auto scroll to the recipe view after clicking on any of the list items.

**Comment by JVJplus** [comment]
@saintaze I think you can find this issue interesting.

**Comment by saintaze** [comment]
I have submitted the PR
